debug = false
render = true
failFast = true
timeout = 2000

[env]
hello = "world"
name = "tom"
host = "http://httpbin.org"
content_type = "application/json"
array = ["a", "b", "c"]


[[order]]
pattern = "examples/post.toml"

[[order]]
pattern = "examples/get.toml"
parallel = true

[[order]]
pattern = "examples/asserts.*"
parallel = true
