title = "asserts"
description = "all supported assertions"

[request]
method = "get"
url = "http://httpbin.org/get"
[request.header]
hello = "world"


[assert]
# status
status = "ok"
status_in = ["bad request", "geteway timeout"]
status_not_in = ["ok", "geteway timeout"]

statusCode = 200
statusCode_in = [400, 500]
statusCode_not_in = [200, 400]
statusCode_lt = 100
statusCode_lte = 100
statusCode_gt = 500
statusCode_gte = 500

# content-length
contentLength = 18
contentLength_lt = 1
contentLength_lte = 1
contentLength_gt = 180
contentLength_gte = 180

# content-type
contentType = "abc"
contentType_in = ["abc"]
contentType_not_in = ["abc"]

# body
body = "HTTPBIN is awesome"
body_contains = "awesome2"
body_not_contains = "awesome"
body_startswith = "A"
body_endswith = "a"
body_not_startswith = "{"
body_not_endswith = "}"

# latency
latency_lt = 0
latency_lte = 0
latency_gt = 100
latency_gte = 100

# proto
proto = "HTTP/2.0"
protoMajor = 2
protoMinor = 0
