debug: false
render: true
failFast: true
timeout: 2000
env:
  hello: world
  name: tom
  host: 'http://httpbin.org'
  content_type: application/json
  array:
    - a
    - b
    - c
order:
  - pattern: examples/http_post.toml
  - pattern: examples/http_get.toml
  - pattern: examples/http_*
