title = "html assert"
description = "html assert"

[request]
method = "get"
url = "http://httpbin.org/html"


[assert]
status = "ok"
statusCode = 200
contentLength_gt = 180
contentType = "text/html"

[[assert.html]]
path = "/html/body/h1"
value =  "Herman Melville - Moby-Dick"

[[assert.html]]
path = "/slideshow/@author"
value =  "Overview"

