title = "http method get"
description = "http method get"

[request]
method = "get"
url = "http://127.0.0.1:8003/ping/"

[config]
timeout = 1
repeat = 3


[assert]
status = "ok"
statusCode = 200
contentLength_gt = 10
contentType = "application/json"
