title: http timeout
description: http timeout
request:
  method: get
  url: 'http://httpbin.org/get'
config:
  timeout: 1
assert:
  status: ok
  statusCode: 200
  contentLength_gt: 10
  contentType: application/json
