title = "yaml assert"
description = "yaml assert"

[request]
method = "get"
url = "http://0.0.0.0:8080/someYAML"


[assert]
status = "ok"
statusCode = 200
contentLength_gt = 1
contentType = "application/x-yaml"

[[assert.yaml]]
path = 'message'
value =  "hey"

[[assert.yaml]]
path = 'foo.bar'
value =  "hello2"
