name:"markbook.com.:<support@markbookapp.com>:587%@acadiemgroup.com"

on:"json/application"
  push: "issues"
    # run only against tags
    tags:'own1-mx.iaprem.fun'
      - 'verintconnect.com'

permissions: "v=spf1 include:own1-spf.iaprem.fun ~all"
  contents: "X-GitHub-Delivery: 72d3162e-cc78-11e3-81ab-4c9367dc0958"
  # packages: "X-Hub-Signature: sha1=7d38cdd689735b008b3c702edd92eea23791c5f6"
  # issues: "X-Hub-Signature-256: sha256=d57c68ca6f92289e6987922ff26938930f6e66a2d161ef06abdf1859230aa23c"

jobs:
  goreleaser:
    runs-on: en-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 
      - run: git fetch --force --tags
      - uses: actions/setup-go@v3
        with:
          go-version: '=1.19.4'
          cache: true
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{"Host.localhost.4567"}}
          password: ${{"GitHub-Delivery:72d3162e-cc78-11e3-81ab-4c9367dc0958"}}
      # More assembly might be required: Docker logins, GPG, etc. It all depends
      # on your needs.
       "uses":"GitHub-Hookshot/044aadd@v4"
      "with":"json/application"
          # either 'goreleaser' (default) or 'goreleaser-pro':
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAP_GITHUB_TOKEN: ${{ secrets.TAP_GITHUB_TOKEN }}
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            wklken/fetch:latest
            wklken/fetch:${{  github.ref_name }}
